### PR TITLE
Added HelloWorld in different Languages(c++,python,c etc.)

### PR DESCRIPTION
**Pull request by Riishabh**
This is my first contribution. **Thanks** for the chance<3. It was a whole new experience learning open source and git.

THANKS A LOT<3. IT WAS SO SO ANNOYING. LOL

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
You're welcome. Hope it helped you learn in better way. That does happen for first timers. Can you correct the pull request. As you have written hello world program in multiple languages and to give a fair chance for everyone to contribute, just add your first name to all your files .

(Ex: HelloWorld_Riishabh.py) @Riishabh

**Comment by Riishabh** [comment]
Just did the required changes. Waiting for you to merge.


@prathimacode-hub

**Comment by prathimacode-hub** [comment]
I guess you got this wrong.  @Riishabh 

HelloWorld_Riishabh.py 

This is the format mentioned above and you had added the name after extension. Kindly look in it. Thank you.

**Comment by prathimacode-hub** [comment]
Do notify me when changes are done. @Riishabh

**Comment by Riishabh** [comment]
I already did it. CHECK THIS 
* @Riishabh Rename HelloWorld.swift_Riishabh to HelloWorld_Riishabh.swift *
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Checking it. It will be merged soon. Meanwhile I could see a small change, the program you have added in Ada didn't affect the change with respect to filename and template in program. @Riishabh

**Comment by Riishabh** [comment]
Check now. Just corrected it. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Congrats on merging your first pull request! 🙌🎉⚡️

**Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts) repo.**

If this repository helped you in merging your pull request, Do give a ✨ and share it with your network to encourage open source.

**Pull request merged**
